//
// Created by emiel on 8/07/20.
//

#ifndef SPECTRALHOOK_CONST_H
#define SPECTRALHOOK_CONST_H

#define MAX_EDICT_BITS 11
#define NUM_ENT_ENTRIES (MAX_EDICT_BITS + 1)
#define INVALID_EHANDLE_INDEX 0xFFFFFFFF
#define ENT_ENTRY_MASK (NUM_ENT_ENTRIES -1)

#endif //SPECTRALHOOK_CONST_H
